// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FFButton: typeof import('@vfastui/fastui')['Button']
    FFCol: typeof import('@vfastui/fastui')['Col']
    FFModal: typeof import('@vfastui/fastui')['Modal']
    FFRow: typeof import('@vfastui/fastui')['Row']
    FFTag: typeof import('@vfastui/fastui')['Tag']
    FFTheme: typeof import('@vfastui/fastui')['Theme']
    FFTooltip: typeof import('@vfastui/fastui')['Tooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ThemeChange: typeof import('./src/components/ThemeChange.vue')['default']
  }
}

export { }
